/**
 * FalconMind — FQL Filter Sanitizer
 *
 * Fixes common invalid FQL patterns generated by AI models.
 * The Alerts v2 API requires ISO 8601 timestamps, not relative time
 * expressions. This utility preprocesses filters before sending.
 */

'use strict';

/**
 * Sanitize an AI-generated FQL filter string before sending to CrowdStrike API.
 *
 * Fixes:
 *  - Relative time tokens like `now-1d`, `now-24h`, `now-7d` → ISO 8601
 *  - Bare `>` or `<` operators on timestamp fields → `>='` ISO date `'`
 *  - `last_updated_timestamp` with invalid formats
 *  - `created_timestamp` with invalid formats
 *  - Unquoted timestamp values
 *
 * @param {string} filter  Raw FQL filter string
 * @returns {string}       Sanitized FQL filter string
 */
function sanitizeFqlFilter(filter) {
    if (!filter || typeof filter !== 'string') return filter;

    let sanitized = filter;

    // ── Fix 1: Replace relative time tokens ──────────────────────────────
    // Patterns like: now-1d, now-7d, now-24h, now-30d, etc.
    sanitized = sanitized.replace(
        /['"]?now-(\d+)([dhm])['"]?/gi,
        (_, amount, unit) => {
            const ms = {
                d: 86400000,
                h: 3600000,
                m: 60000,
            };
            const multiplier = ms[unit.toLowerCase()] || ms.d;
            const date = new Date(Date.now() - parseInt(amount) * multiplier);
            return `'${date.toISOString()}'`;
        }
    );

    // ── Fix 2: Ensure timestamp comparison operators use >= / <= ─────────
    // The Alerts v2 API uses `>=` not `>` for timestamp comparisons
    sanitized = sanitized.replace(
        /(last_updated_timestamp|created_timestamp|first_occurrence|timestamp):(?:>|>=)\s*/gi,
        (_, field) => `${field}:>=`
    );

    // ── Fix 3: Remove empty filter clauses (e.g., "status:'new'+") ──────
    sanitized = sanitized.replace(/\+$/g, '');
    sanitized = sanitized.replace(/^\+/g, '');

    return sanitized;
}

module.exports = { sanitizeFqlFilter };
